name: Build & Deploy Dev

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-pwa-dev:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '22'
      - run: npm install
      - run: npx quasar build -m pwa
      - name: Deploy PWA Dev to Surge
        run: |
          npm install -g surge@0.24.6
          export SURGE_TOKEN=935aec63550df73f541822b03ea28d26
          surge dist/pwa --domain=${{ github.event.repository.name }}-dev.huclin.surge.sh
          surge dist/pwa --domain=${{ github.event.repository.name }}-dev.surge.sh
